# Generated by Django 4.0.4 on 2022-05-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='nom_de_categorie',
            new_name='nom_de_categorie1',
        ),
        migrations.AddField(
            model_name='categorie',
            name='nom_de_categorie2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='nom_de_categorie3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='nom_de_categorie4',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
