# Generated by Django 4.0.4 on 2022-05-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_rename_nom_de_categorie_categorie_nom_de_categorie1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='Image',
            field=models.FileField(upload_to=''),
        ),
    ]
