# Generated by Django 4.0.4 on 2022-05-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libele', models.CharField(max_length=255)),
                ('Description', models.TextField(max_length=500)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.ImageField(upload_to='')),
                ('Nom', models.CharField(max_length=255)),
                ('fb_link', models.URLField()),
                ('insta_link', models.URLField()),
                ('twitter_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=255)),
                ('Phone_number', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Jours', models.DateField()),
                ('Maps', models.URLField()),
                ('Person', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.ImageField(upload_to='')),
                ('copyright', models.TextField()),
                ('Section_banner_image', models.ImageField(upload_to='')),
                ('Description_footer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=255)),
                ('Image', models.ImageField(upload_to='')),
                ('Description', models.TextField(max_length=500)),
                ('Metier', models.CharField(max_length=255)),
            ],
        ),
    ]
