# Generated by Django 4.0.4 on 2022-05-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteInfo', '0002_remove_network_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dial_code',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
