# Generated by Django 4.0.4 on 2022-05-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteInfo', '0004_alter_reservation_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='tilte',
        ),
        migrations.AddField(
            model_name='site',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='Image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='Section_banner_image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='Image',
            field=models.FileField(upload_to=''),
        ),
    ]
